name: Auto build Aseprite

on:
  push:
    branches: ["main"]

jobs:
  auto-build:
    name: Auto build Aseprite for Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download & Build Aseprite
        run: |
          python main.py
